### ISSUE TITLE
Make repository public

### ISSUE THREAD

**Issue by jonoyuan** [MUSA-620-Spring-2019/final-project-lin-wang-yuan#1]
@nickhand Can you make this repository public? We're not able to connect it to binder in order to create the panel app.

Link to binder app (with 404 error):
[![image](https://user-images.githubusercontent.com/22150566/57668874-dea02880-75d6-11e9-84ed-58c3d5192ce1.png)
](https://mybinder.org/v2/gh/MUSA-620-Spring-2019/final-project-lin-wang-yuan/master?urlpath=final.ipynb)

**Comment by nickhand** [comment]
Done!
